#!/usr/bin/env python3
"""Transcribe libaom's unrolled 1-D FFT/IFFT butterfly macros to Rust.

Source: `reference/libaom/aom_dsp/fft_common.h` — the `GEN_FFT_{2,4,8,16,32}`
and `GEN_IFFT_{2,4,8,16,32}` macros. Each macro is a *fully unrolled*,
straight-line real->complex (or complex->real) transform of one column, using
ONLY separate add/sub/mul (verified: the reference build's `fft.c.o` contains
ZERO fma instructions — gcc 15.2 `-std=c11` does not contract). So a strict-f32
Rust transcription that keeps `add`/`sub`/`mul` as distinct roundings is
bit-identical to the scalar AND the RTCD-dispatched SSE2/AVX2 oracle (the SIMD
paths use `_mm*_add/sub/mul_ps` intrinsics — also non-fused, lane-parallel).

The transcription is deliberately mechanical (verbatim op order) so the port
carries no re-derivation risk; the `noise_fft_diff` differential vs the real
exported `aom_fft*x*_float` / `aom_ifft*x*_float` is the proof of byte-identity.

Usage: python3 xtask/transcribe_noise_fft.py > /tmp/noise_fft_1d.rs
Then the generated block is pasted into `crates/aom-encode/src/noise_fft.rs`.
"""
import re
import sys

HDR = "/root/aom-rs/reference/libaom/aom_dsp/fft_common.h"


def read_macro_body(text, macro):
    """Return the joined (continuation-stripped) text of `#define macro(...)`."""
    m = re.search(r"#define\s+" + re.escape(macro) + r"\b", text)
    if not m:
        raise SystemExit(f"macro {macro} not found")
    i = m.start()
    # Collect continuation lines (each ending in backslash) plus the final line.
    lines = []
    for line in text[i:].splitlines():
        lines.append(line.rstrip("\n"))
        if not line.rstrip().endswith("\\"):
            break
    joined = " ".join(l.rstrip().rstrip("\\").strip() for l in lines)
    # Body is between the first '{' after the signature and the final '}'.
    lb = joined.index("{")
    rb = joined.rindex("}")
    return joined[lb + 1 : rb]


def conv_expr(e):
    """Inner C-expression -> Rust: load/constant unwrap, f-suffix, kWeight rename."""
    e = re.sub(r"load\(input \+ (\d+) \* stride\)", r"input[\1 * stride]", e)
    e = re.sub(r"constant\(([^)]*)\)", r"\1", e)
    e = re.sub(r"(\d+\.\d+)f\b", r"\1f32", e)  # 0.707107f -> 0.707107f32
    e = e.replace("kWeight", "kw")
    e = re.sub(r"\s+", " ", e).strip()
    return e


def transcribe(text, macro, fn):
    body = read_macro_body(text, macro)
    stmts = [s.strip() for s in body.split(";") if s.strip()]
    out = [f"pub(super) fn {fn}(input: &[f32], output: &mut [f32], stride: usize) {{"]
    for s in stmts:
        s = re.sub(r"\s+", " ", s)
        m = re.match(r"const T_VEC (\w+)\[2\] = \{(.*)\}$", s)
        if m:
            name = m.group(1).replace("kWeight", "kw")
            out.append(f"    let {name}: [f32; 2] = [{conv_expr(m.group(2))}];")
            continue
        m = re.match(r"const T_VEC (\w+) = (.*)$", s)
        if m:
            name = m.group(1).replace("kWeight", "kw")
            out.append(f"    let {name} = {conv_expr(m.group(2))};")
            continue
        m = re.match(r"store\(output \+ (\d+) \* stride, (.*)\)$", s)
        if m:
            out.append(f"    output[{m.group(1)} * stride] = {conv_expr(m.group(2))};")
            continue
        raise SystemExit(f"unhandled statement in {macro}: {s!r}")
    out.append("}")
    return "\n".join(out)


def main():
    with open(HDR) as f:
        text = f.read()
    # Emitted as an `include!`-able fragment (no outer `mod`): noise_fft.rs
    # wraps it in `mod gen { ... }` with the clippy allows.
    print("// @generated by xtask/transcribe_noise_fft.py from")
    print("// reference/libaom/aom_dsp/fft_common.h GEN_FFT_*/GEN_IFFT_* macros.")
    print("// DO NOT EDIT BY HAND -- re-run the script to regenerate.")
    print("//")
    print("// Each fn is a fully-unrolled, straight-line 1-D transform of one column")
    print("// using only distinct add/sub/mul roundings (no FMA -- verified: the")
    print("// reference build's fft.c.o has zero fma instructions). Bit-identical to")
    print("// the scalar C AND the RTCD SSE2/AVX2 oracle (SIMD paths are non-fused,")
    print("// lane-parallel). Proven by tests/noise_fft_diff.rs.")
    print("use super::{add, sub, mul};")
    for n in (2, 4, 8, 16, 32):
        print()
        print(transcribe(text, f"GEN_FFT_{n}", f"fft1d_{n}"))
    for n in (2, 4, 8, 16, 32):
        print()
        print(transcribe(text, f"GEN_IFFT_{n}", f"ifft1d_{n}"))


if __name__ == "__main__":
    main()
