#!/usr/bin/env python3
"""Transcribe the curvefit model-rd tables from libaom's av1/encoder/rd.c into
crates/aom-encode/src/curvfit_tables.rs.

Tables: interp_rgrid_curv[4][65], interp_dgrid_curv[3][65] (f64 literals kept
verbatim — the doubles must be bit-identical), and
bsize_curvfit_model_cat_lookup[BLOCK_SIZES_ALL].

Usage: python3 xtask/transcribe_curvfit.py <path-to-libaom> > \
           crates/aom-encode/src/curvfit_tables.rs
"""
import re
import sys


def extract_table(src: str, name: str, rows: int, cols: int, decl_rows=None):
    i = src.index(f"{name}[{decl_rows or rows}][{cols}]")
    j = src.index("};", i)
    body = src[i:j]
    nums = re.findall(r"-?\d+\.\d+", body)
    assert len(nums) == rows * cols, (name, len(nums))
    return [nums[r * cols:(r + 1) * cols] for r in range(rows)]


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "reference/libaom"
    src = open(f"{root}/av1/encoder/rd.c").read()

    rgrid = extract_table(src, "interp_rgrid_curv", 4, 65)
    # Declared [3][65] in C but only 2 rows are initialized (row 2 is the
    # implicit-zero tail and is unreachable: dcat = sse_norm > 16.0 ∈ {0,1}).
    dgrid = extract_table(src, "interp_dgrid_curv", 2, 65, decl_rows=3)

    i = src.index("bsize_curvfit_model_cat_lookup[BLOCK_SIZES_ALL]")
    j = src.index("};", i)
    cats = re.findall(r"\d+", src[i:j].split("=")[1])
    assert len(cats) == 22, cats

    print("//! GENERATED by xtask/transcribe_curvfit.py — the curvefit model-rd")
    print("//! interpolation grids from libaom v3.14.1 `av1/encoder/rd.c`")
    print("//! (`interp_rgrid_curv` / `interp_dgrid_curv` /")
    print("//! `bsize_curvfit_model_cat_lookup`). Do not edit by hand; the f64")
    print("//! literals must stay bit-identical to the C doubles.")
    print()
    print("/// `bsize_curvfit_model_cat_lookup[BLOCK_SIZES_ALL]` (rd.c:964).")
    print(f"pub const BSIZE_CURVFIT_MODEL_CAT: [usize; 22] = [{', '.join(cats)}];")
    print()

    def emit(name, doc, table):
        rows, cols = len(table), len(table[0])
        print(f"/// `{doc}` (rd.c).")
        print(f"pub const {name}: [[f64; {cols}]; {rows}] = [")
        for row in table:
            print("    [")
            for k in range(0, cols, 5):
                print("        " + " ".join(f"{v}," for v in row[k:k + 5]))
            print("    ],")
        print("];")
        print()

    emit("INTERP_RGRID_CURV", "interp_rgrid_curv[4][65]", rgrid)
    emit("INTERP_DGRID_CURV", "interp_dgrid_curv[3][65] (initialized rows only; row 2 is an unreachable zero tail)", dgrid)


if __name__ == "__main__":
    main()
