#!/usr/bin/env python3
"""Transcribe the inter var-tx 2D tx-type prune NNs (prune_tx_2D, tx_search.c:1541)
from libaom's tx_prune_model_weights.h into Rust — the NON-V2 (default, !CONFIG_NN
_V2) `av1_tx_type_nnconfig_map_hor` / `_ver` (tx_prune_model_weights.h:2324/2346).

Each is a `num_inputs -> num_hidden (ReLU) -> 4` NN (av1_nn_predict). Only 9 tx
sizes have a nnconfig (4x4, 8x8, 16x16[shared hor/ver], 4x8, 8x4, 8x16, 16x8,
4x16, 16x4); the rest map to NULL and prune_tx_2D early-returns.

Faithful mechanical transcription; correctness enforced by the length asserts here
plus the `prune_tx_2d_diff` differential (real ref_nn_predict + ref-exported
helpers).
"""

import re

SRC = "reference/libaom/av1/encoder/tx_prune_model_weights.h"
src = open(SRC).read()


def floats(body):
    return [v[:-1] for v in re.findall(r"-?\d+\.?\d*(?:e-?\d+)?f", body)]


def named_array(name, expected_len):
    m = re.search(
        r"static const float\s+" + re.escape(name) + r"\s*(?:\[[^\]]*\]\s*)+=\s*\{(.*?)\};",
        src,
        re.S,
    )
    assert m, f"array not found: {name}"
    vals = floats(m.group(1))
    assert len(vals) == expected_len, (name, len(vals), expected_len)
    return vals


# (cfg tag, num_inputs, num_hidden). num_outputs is always 4.
CONFIGS = [
    ("4x4_hor", 4, 8), ("4x4_ver", 4, 8),
    ("8x8_hor", 8, 16), ("8x8_ver", 8, 16),
    ("16x16", 8, 16),
    ("4x8_hor", 4, 8), ("4x8_ver", 8, 16),
    ("8x4_hor", 8, 16), ("8x4_ver", 4, 8),
    ("8x16_hor", 8, 16), ("8x16_ver", 8, 16),
    ("16x8_hor", 8, 16), ("16x8_ver", 8, 16),
    ("4x16_hor", 4, 8), ("4x16_ver", 8, 16),
    ("16x4_hor", 8, 16), ("16x4_ver", 4, 8),
]

# tx_size -> (hor cfg, ver cfg) or None (av1_tx_type_nnconfig_map_hor/ver).
HOR = [
    "4x4_hor", "8x8_hor", "16x16", None, None, "4x8_hor", "8x4_hor", "8x16_hor",
    "16x8_hor", None, None, None, None, "4x16_hor", "16x4_hor", None, None, None, None,
]
VER = [
    "4x4_ver", "8x8_ver", "16x16", None, None, "4x8_ver", "8x4_ver", "8x16_ver",
    "16x8_ver", None, None, None, None, "4x16_ver", "16x4_ver", None, None, None, None,
]
TX_NAMES = [
    "TX_4X4", "TX_8X8", "TX_16X16", "TX_32X32", "TX_64X64", "TX_4X8", "TX_8X4",
    "TX_8X16", "TX_16X8", "TX_16X32", "TX_32X16", "TX_32X64", "TX_64X32", "TX_4X16",
    "TX_16X4", "TX_8X32", "TX_32X8", "TX_16X64", "TX_64X16",
]


def fmt(vals, per_line=8):
    out = []
    for i in range(0, len(vals), per_line):
        out.append("    " + ", ".join(f"{v}f32" for v in vals[i : i + per_line]) + ",")
    return "\n".join(out)


def rid(tag):
    return tag.upper().replace("X", "X")


parts = [
    "//! GENERATED by `xtask/transcribe_prune_tx_2d_nn.py` — do not hand-edit.",
    "//!",
    "//! The inter var-tx 2D tx-type prune NNs (`prune_tx_2D`, tx_search.c:1541),",
    "//! non-V2 `av1_tx_type_nnconfig_map_hor`/`_ver`. Each is",
    "//! `num_inputs -> num_hidden (ReLU) -> 4` (`av1_nn_predict`, node-major w0).",
    "",
    "/// One hor/ver tx-type NN (`NN_CONFIG`, 1 hidden layer, 4 outputs).",
    "pub struct PruneTx2dNn {",
    "    pub num_inputs: usize,",
    "    pub num_hidden: usize,",
    "    /// `[num_hidden * num_inputs]`, node-major.",
    "    pub w0: &'static [f32],",
    "    /// `[num_hidden]`.",
    "    pub b0: &'static [f32],",
    "    /// `[4 * num_hidden]`, output-node-major.",
    "    pub w1: &'static [f32],",
    "    /// `[4]`.",
    "    pub b1: &'static [f32],",
    "}",
    "",
]

for tag, ni, nh in CONFIGS:
    w0 = named_array(f"av1_tx_type_nn_weights_{tag}_layer0", ni * nh)
    b0 = named_array(f"av1_tx_type_nn_bias_{tag}_layer0", nh)
    w1 = named_array(f"av1_tx_type_nn_weights_{tag}_layer1", nh * 4)
    b1 = named_array(f"av1_tx_type_nn_bias_{tag}_layer1", 4)
    r = rid(tag)
    parts.append(f"const W0_{r}: [f32; {ni * nh}] = [\n{fmt(w0)}\n];")
    parts.append(f"const B0_{r}: [f32; {nh}] = [\n{fmt(b0)}\n];")
    parts.append(f"const W1_{r}: [f32; {nh * 4}] = [\n{fmt(w1)}\n];")
    parts.append(f"const B1_{r}: [f32; 4] = [\n{fmt(b1)}\n];")
    parts.append("")

cfgdims = {t: (i, h) for t, i, h in CONFIGS}


def entry(tag):
    if tag is None:
        return "    None,"
    r = rid(tag)
    ni, nh = cfgdims[tag]
    return (
        f"    Some(PruneTx2dNn {{ num_inputs: {ni}, num_hidden: {nh}, "
        f"w0: &W0_{r}, b0: &B0_{r}, w1: &W1_{r}, b1: &B1_{r} }}),"
    )


for name, arr in (("PRUNE_TX_2D_HOR", HOR), ("PRUNE_TX_2D_VER", VER)):
    parts.append(f"/// `av1_tx_type_nnconfig_map_{name.split('_')[-1].lower()}` (None where NULL).")
    parts.append(f"pub static {name}: [Option<PruneTx2dNn>; 19] = [")
    for i, tag in enumerate(arr):
        parts.append(entry(tag) + f"  // {TX_NAMES[i]}")
    parts.append("];")
    parts.append("")

open("crates/aom-encode/src/prune_tx_2d_nn_weights.rs", "w").write("\n".join(parts))
print(f"wrote crates/aom-encode/src/prune_tx_2d_nn_weights.rs ({len(CONFIGS)} NNs)")
