#!/usr/bin/env python3
"""Transcribe the inter var-tx split-prediction NNs (ml_predict_tx_split,
tx_search.c:1755) from libaom's tx_prune_model_weights.h into Rust.

`av1_tx_split_nnconfig_map[TX_SIZES_ALL]` maps each tx size to a 1-hidden-layer
NN (num_inputs -> num_hidden ReLU -> 1 output). Unlike the intra tx-depth NN there
is NO feature normalization — the raw `get_mean_dev_features` output feeds
`av1_nn_predict` directly. TX_4X4 maps to NULL (predictor returns -1).

Faithful mechanical transcription; correctness is enforced by the shape asserts
here plus the real-C `shim_ml_predict_tx_split` differential (a future
`tx_split_nn_diff` test) that will validate the port's NN eval + wiring.
"""

import re

SRC = "reference/libaom/av1/encoder/tx_prune_model_weights.h"
src = open(SRC).read()


def floats(body):
    return [v[:-1] for v in re.findall(r"-?\d+\.?\d*(?:e-?\d+)?f", body)]


def named_array(name, expected_len):
    m = re.search(
        r"static const float\s+" + re.escape(name) + r"\s*(?:\[[^\]]*\]\s*)+=\s*\{(.*?)\};",
        src,
        re.S,
    )
    assert m, f"array not found: {name}"
    vals = floats(m.group(1))
    assert len(vals) == expected_len, (name, len(vals), expected_len)
    return vals


# (nnconfig tag, num_inputs, num_hidden) — verified from the NN_CONFIG structs.
CONFIGS = [
    ("4x8", 8, 16),
    ("8x8", 12, 12),
    ("8x16", 8, 64),
    ("16x16", 12, 24),
    ("32x32", 12, 32),
    ("64x64", 12, 32),
    ("4x16", 8, 16),
    ("16x32", 8, 32),
    ("32x64", 8, 32),
    ("8x32", 8, 24),
    ("16x64", 8, 16),
]

# av1_tx_split_nnconfig_map[TX_SIZES_ALL] — tx_size index -> nnconfig tag (or None).
TX_MAP = [
    None,     # TX_4X4
    "8x8",    # TX_8X8
    "16x16",  # TX_16X16
    "32x32",  # TX_32X32
    "64x64",  # TX_64X64
    "4x8",    # TX_4X8
    "4x8",    # TX_8X4
    "8x16",   # TX_8X16
    "8x16",   # TX_16X8
    "16x32",  # TX_16X32
    "16x32",  # TX_32X16
    "32x64",  # TX_32X64
    "32x64",  # TX_64X32
    "4x16",   # TX_4X16
    "4x16",   # TX_16X4
    "8x32",   # TX_8X32
    "8x32",   # TX_32X8
    "16x64",  # TX_16X64
    "16x64",  # TX_64X16
]


def fmt(vals, per_line=8):
    out = []
    for i in range(0, len(vals), per_line):
        out.append("    " + ", ".join(f"{v}f32" for v in vals[i : i + per_line]) + ",")
    return "\n".join(out)


def rust_ident(tag):
    return tag.upper()


parts = [
    "//! GENERATED by `xtask/transcribe_tx_split_nn.py` — do not hand-edit.",
    "//!",
    "//! The inter var-tx split-prediction NNs (`ml_predict_tx_split`,",
    "//! tx_search.c:1755): `av1_tx_split_nnconfig_map[tx_size]` -> a",
    "//! `num_inputs -> num_hidden (ReLU) -> 1` NN. Layer-0 weights are the flat",
    "//! `av1_tx_split_nn_weights_{sz}_layer0[num_inputs * num_hidden]` (the",
    "//! `av1_nn_predict` layout: node-major, `w0[node*num_inputs + input]`).",
    "//! No feature normalization (raw `get_mean_dev_features`).",
    "",
    "/// One tx-split NN (`NN_CONFIG`, 1 hidden layer).",
    "pub struct TxSplitNn {",
    "    pub num_inputs: usize,",
    "    pub num_hidden: usize,",
    "    /// `[num_hidden * num_inputs]`, node-major.",
    "    pub w0: &'static [f32],",
    "    /// `[num_hidden]`.",
    "    pub b0: &'static [f32],",
    "    /// `[num_hidden]` (output layer weights, 1 output).",
    "    pub w1: &'static [f32],",
    "    /// output-layer bias.",
    "    pub b1: f32,",
    "}",
    "",
]

for tag, ni, nh in CONFIGS:
    w0 = named_array(f"av1_tx_split_nn_weights_{tag}_layer0", ni * nh)
    b0 = named_array(f"av1_tx_split_nn_bias_{tag}_layer0", nh)
    w1 = named_array(f"av1_tx_split_nn_weights_{tag}_layer1", nh)
    b1 = named_array(f"av1_tx_split_nn_bias_{tag}_layer1", 1)
    r = rust_ident(tag)
    parts.append(f"const W0_{r}: [f32; {ni * nh}] = [\n{fmt(w0)}\n];")
    parts.append(f"const B0_{r}: [f32; {nh}] = [\n{fmt(b0)}\n];")
    parts.append(f"const W1_{r}: [f32; {nh}] = [\n{fmt(w1)}\n];")
    parts.append(f"const B1_{r}: f32 = {b1[0]}f32;")
    parts.append("")


def entry(tag):
    if tag is None:
        return "    None,"
    r = rust_ident(tag)
    ni = dict((t, i) for t, i, _ in CONFIGS)[tag]
    nh = dict((t, h) for t, _, h in CONFIGS)[tag]
    return (
        f"    Some(TxSplitNn {{ num_inputs: {ni}, num_hidden: {nh}, "
        f"w0: &W0_{r}, b0: &B0_{r}, w1: &W1_{r}, b1: B1_{r} }}),"
    )


parts.append("/// `av1_tx_split_nnconfig_map[TX_SIZES_ALL]` (None = TX_4X4, no predictor).")
parts.append("pub static TX_SPLIT_NN: [Option<TxSplitNn>; 19] = [")
tx_names = [
    "TX_4X4", "TX_8X8", "TX_16X16", "TX_32X32", "TX_64X64", "TX_4X8", "TX_8X4",
    "TX_8X16", "TX_16X8", "TX_16X32", "TX_32X16", "TX_32X64", "TX_64X32", "TX_4X16",
    "TX_16X4", "TX_8X32", "TX_32X8", "TX_16X64", "TX_64X16",
]
for i, tag in enumerate(TX_MAP):
    parts.append(entry(tag) + f"  // {tx_names[i]}")
parts.append("];")
parts.append("")

open("crates/aom-encode/src/tx_split_nn_weights.rs", "w").write("\n".join(parts))
print(f"wrote crates/aom-encode/src/tx_split_nn_weights.rs ({len(CONFIGS)} nnconfigs)")
