#!/usr/bin/env python3
"""Transcribe the intra 8x8 tx-depth pruning NN (ml_predict_intra_tx_depth_prune,
tx_search.c:2823) weight tables from libaom's tx_prune_model_weights.h into Rust.

Tables (all under `#if !CONFIG_REALTIME_ONLY`, tx_prune_model_weights.h:3320+):
  - av1_intra_tx_split_8x8_mean[14] / _std[14]  (feature normalization)
  - av1_intra_tx_split_nn_weights_8x8_layer0[14*16] + bias[16]
  - av1_intra_tx_split_nn_weights_8x8_layer1[16] + bias[1]
  - av1_intra_tx_prune_nn_thresh_8x8[2]  ({-0.405465, 0.405465})

Faithful mechanical transcription; correctness is enforced by the shape
assertions here plus the real-C `shim_nn_predict` differential
(intra_tx_depth_nn_diff test) and the speed-6 byte gate.
"""

import re

SRC = "reference/libaom/av1/encoder/tx_prune_model_weights.h"
src = open(SRC).read()


def floats(body):
    return [float(v[:-1]) for v in re.findall(r"-?\d+\.?\d*(?:e-?\d+)?f", body)]


def named_array(name, expected_len):
    m = re.search(
        r"static const float\s+" + re.escape(name) + r"\s*(?:\[[^\]]*\]\s*)+=\s*\{(.*?)\};",
        src,
        re.S,
    )
    assert m, f"array not found: {name}"
    vals = floats(m.group(1))
    assert len(vals) == expected_len, (name, len(vals), expected_len)
    return vals


NUM_FEATURES = 14
HIDDEN = 16

mean = named_array("av1_intra_tx_split_8x8_mean", NUM_FEATURES)
std = named_array("av1_intra_tx_split_8x8_std", NUM_FEATURES)
w0 = named_array("av1_intra_tx_split_nn_weights_8x8_layer0", NUM_FEATURES * HIDDEN)
b0 = named_array("av1_intra_tx_split_nn_bias_8x8_layer0", HIDDEN)
w1 = named_array("av1_intra_tx_split_nn_weights_8x8_layer1", HIDDEN)
b1 = named_array("av1_intra_tx_split_nn_bias_8x8_layer1", 1)
thresh = named_array("av1_intra_tx_prune_nn_thresh_8x8", 2)


def fmt(vals, per_line=6):
    out = []
    for i in range(0, len(vals), per_line):
        out.append("    " + ", ".join(f"{v}f32" for v in vals[i : i + per_line]) + ",")
    return "\n".join(out)


rs = f"""//! GENERATED by `xtask/transcribe_intra_tx_nn.py` — do not hand-edit.
//!
//! The intra 8x8 tx-depth pruning NN (`ml_predict_intra_tx_depth_prune`,
//! tx_search.c:2823): feature normalization tables + a 14->16(ReLU)->1
//! sequential net + the SPLIT/LARGEST score thresholds, transcribed from
//! `av1_intra_tx_split_*` / `av1_intra_tx_prune_nn_thresh_8x8`
//! (tx_prune_model_weights.h:3320-3415, libaom v3.14.1).

/// `NUM_INTRA_TX_SPLIT_FEATURES`.
pub const NUM_FEATURES: usize = {NUM_FEATURES};
/// `NUM_INTRA_TX_SPLIT_HIDDEN_NODES` (one hidden layer).
pub const NUM_HIDDEN: usize = {HIDDEN};

/// `av1_intra_tx_split_8x8_mean`.
pub const MEAN: [f32; NUM_FEATURES] = [
{fmt(mean)}
];

/// `av1_intra_tx_split_8x8_std`.
pub const STD: [f32; NUM_FEATURES] = [
{fmt(std)}
];

/// `av1_intra_tx_split_nn_weights_8x8_layer0` (row-major: hidden node n reads
/// `W0[n*NUM_FEATURES..]` per `av1_nn_predict_c`'s
/// `weights[node * num_inputs + i]` indexing).
pub const W0: [f32; NUM_FEATURES * NUM_HIDDEN] = [
{fmt(w0)}
];

/// `av1_intra_tx_split_nn_bias_8x8_layer0`.
pub const B0: [f32; NUM_HIDDEN] = [
{fmt(b0)}
];

/// `av1_intra_tx_split_nn_weights_8x8_layer1`.
pub const W1: [f32; NUM_HIDDEN] = [
{fmt(w1)}
];

/// `av1_intra_tx_split_nn_bias_8x8_layer1`.
pub const B1: [f32; 1] = [
{fmt(b1)}
];

/// `av1_intra_tx_prune_nn_thresh_8x8`: `score <= [0]` -> TX_PRUNE_SPLIT,
/// `score > [1]` -> TX_PRUNE_LARGEST.
pub const PRUNE_THRESH: [f32; 2] = [
{fmt(thresh)}
];
"""

open("crates/aom-encode/src/intra_tx_nn_weights.rs", "w").write(rs)
print(f"wrote crates/aom-encode/src/intra_tx_nn_weights.rs "
      f"({NUM_FEATURES} features, {HIDDEN} hidden)")
