/* GENERATED highbd SAD/variance shim (CONVERT_TO_BYTEPTR). Oracle only. */
#include <stdint.h>
#include "aom_ports/mem.h"
unsigned int aom_highbd_sad4x4_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance4x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance4x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance4x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad4x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance4x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance4x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance4x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad4x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance4x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance4x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance4x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad8x4_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance8x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance8x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance8x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad8x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance8x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance8x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance8x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad8x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance8x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance8x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance8x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad8x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance8x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance8x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance8x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad16x4_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance16x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance16x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance16x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad16x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance16x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance16x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance16x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad16x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance16x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance16x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance16x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad16x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance16x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance16x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance16x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad16x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance16x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance16x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance16x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad32x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance32x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance32x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance32x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad32x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance32x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance32x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance32x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad32x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance32x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance32x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance32x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad32x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance32x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance32x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance32x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad64x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance64x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance64x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance64x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad64x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance64x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance64x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance64x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad64x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance64x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance64x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance64x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad64x128_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance64x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance64x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance64x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad128x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance128x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance128x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance128x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int aom_highbd_sad128x128_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_highbd_8_variance128x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_variance128x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_variance128x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
unsigned int shim_hbd_sad(int i,const uint16_t*s,int ss,const uint16_t*r,int rs){
  const uint8_t* sp=CONVERT_TO_BYTEPTR(s); const uint8_t* rp=CONVERT_TO_BYTEPTR(r);
  switch(i){
  case 0: return aom_highbd_sad4x4_c(sp,ss,rp,rs);
  case 1: return aom_highbd_sad4x8_c(sp,ss,rp,rs);
  case 2: return aom_highbd_sad4x16_c(sp,ss,rp,rs);
  case 3: return aom_highbd_sad8x4_c(sp,ss,rp,rs);
  case 4: return aom_highbd_sad8x8_c(sp,ss,rp,rs);
  case 5: return aom_highbd_sad8x16_c(sp,ss,rp,rs);
  case 6: return aom_highbd_sad8x32_c(sp,ss,rp,rs);
  case 7: return aom_highbd_sad16x4_c(sp,ss,rp,rs);
  case 8: return aom_highbd_sad16x8_c(sp,ss,rp,rs);
  case 9: return aom_highbd_sad16x16_c(sp,ss,rp,rs);
  case 10: return aom_highbd_sad16x32_c(sp,ss,rp,rs);
  case 11: return aom_highbd_sad16x64_c(sp,ss,rp,rs);
  case 12: return aom_highbd_sad32x8_c(sp,ss,rp,rs);
  case 13: return aom_highbd_sad32x16_c(sp,ss,rp,rs);
  case 14: return aom_highbd_sad32x32_c(sp,ss,rp,rs);
  case 15: return aom_highbd_sad32x64_c(sp,ss,rp,rs);
  case 16: return aom_highbd_sad64x16_c(sp,ss,rp,rs);
  case 17: return aom_highbd_sad64x32_c(sp,ss,rp,rs);
  case 18: return aom_highbd_sad64x64_c(sp,ss,rp,rs);
  case 19: return aom_highbd_sad64x128_c(sp,ss,rp,rs);
  case 20: return aom_highbd_sad128x64_c(sp,ss,rp,rs);
  case 21: return aom_highbd_sad128x128_c(sp,ss,rp,rs);
  default: return 0;}}
uint32_t shim_hbd_var(int i,int bd,const uint16_t*a,int as,const uint16_t*b,int bs,uint32_t*sse){
  const uint8_t* ap=CONVERT_TO_BYTEPTR(a); const uint8_t* bp=CONVERT_TO_BYTEPTR(b);
  switch(i*3 + (bd==8?0:bd==10?1:2)){
  case 0: return aom_highbd_8_variance4x4_c(ap,as,bp,bs,sse);
  case 1: return aom_highbd_10_variance4x4_c(ap,as,bp,bs,sse);
  case 2: return aom_highbd_12_variance4x4_c(ap,as,bp,bs,sse);
  case 3: return aom_highbd_8_variance4x8_c(ap,as,bp,bs,sse);
  case 4: return aom_highbd_10_variance4x8_c(ap,as,bp,bs,sse);
  case 5: return aom_highbd_12_variance4x8_c(ap,as,bp,bs,sse);
  case 6: return aom_highbd_8_variance4x16_c(ap,as,bp,bs,sse);
  case 7: return aom_highbd_10_variance4x16_c(ap,as,bp,bs,sse);
  case 8: return aom_highbd_12_variance4x16_c(ap,as,bp,bs,sse);
  case 9: return aom_highbd_8_variance8x4_c(ap,as,bp,bs,sse);
  case 10: return aom_highbd_10_variance8x4_c(ap,as,bp,bs,sse);
  case 11: return aom_highbd_12_variance8x4_c(ap,as,bp,bs,sse);
  case 12: return aom_highbd_8_variance8x8_c(ap,as,bp,bs,sse);
  case 13: return aom_highbd_10_variance8x8_c(ap,as,bp,bs,sse);
  case 14: return aom_highbd_12_variance8x8_c(ap,as,bp,bs,sse);
  case 15: return aom_highbd_8_variance8x16_c(ap,as,bp,bs,sse);
  case 16: return aom_highbd_10_variance8x16_c(ap,as,bp,bs,sse);
  case 17: return aom_highbd_12_variance8x16_c(ap,as,bp,bs,sse);
  case 18: return aom_highbd_8_variance8x32_c(ap,as,bp,bs,sse);
  case 19: return aom_highbd_10_variance8x32_c(ap,as,bp,bs,sse);
  case 20: return aom_highbd_12_variance8x32_c(ap,as,bp,bs,sse);
  case 21: return aom_highbd_8_variance16x4_c(ap,as,bp,bs,sse);
  case 22: return aom_highbd_10_variance16x4_c(ap,as,bp,bs,sse);
  case 23: return aom_highbd_12_variance16x4_c(ap,as,bp,bs,sse);
  case 24: return aom_highbd_8_variance16x8_c(ap,as,bp,bs,sse);
  case 25: return aom_highbd_10_variance16x8_c(ap,as,bp,bs,sse);
  case 26: return aom_highbd_12_variance16x8_c(ap,as,bp,bs,sse);
  case 27: return aom_highbd_8_variance16x16_c(ap,as,bp,bs,sse);
  case 28: return aom_highbd_10_variance16x16_c(ap,as,bp,bs,sse);
  case 29: return aom_highbd_12_variance16x16_c(ap,as,bp,bs,sse);
  case 30: return aom_highbd_8_variance16x32_c(ap,as,bp,bs,sse);
  case 31: return aom_highbd_10_variance16x32_c(ap,as,bp,bs,sse);
  case 32: return aom_highbd_12_variance16x32_c(ap,as,bp,bs,sse);
  case 33: return aom_highbd_8_variance16x64_c(ap,as,bp,bs,sse);
  case 34: return aom_highbd_10_variance16x64_c(ap,as,bp,bs,sse);
  case 35: return aom_highbd_12_variance16x64_c(ap,as,bp,bs,sse);
  case 36: return aom_highbd_8_variance32x8_c(ap,as,bp,bs,sse);
  case 37: return aom_highbd_10_variance32x8_c(ap,as,bp,bs,sse);
  case 38: return aom_highbd_12_variance32x8_c(ap,as,bp,bs,sse);
  case 39: return aom_highbd_8_variance32x16_c(ap,as,bp,bs,sse);
  case 40: return aom_highbd_10_variance32x16_c(ap,as,bp,bs,sse);
  case 41: return aom_highbd_12_variance32x16_c(ap,as,bp,bs,sse);
  case 42: return aom_highbd_8_variance32x32_c(ap,as,bp,bs,sse);
  case 43: return aom_highbd_10_variance32x32_c(ap,as,bp,bs,sse);
  case 44: return aom_highbd_12_variance32x32_c(ap,as,bp,bs,sse);
  case 45: return aom_highbd_8_variance32x64_c(ap,as,bp,bs,sse);
  case 46: return aom_highbd_10_variance32x64_c(ap,as,bp,bs,sse);
  case 47: return aom_highbd_12_variance32x64_c(ap,as,bp,bs,sse);
  case 48: return aom_highbd_8_variance64x16_c(ap,as,bp,bs,sse);
  case 49: return aom_highbd_10_variance64x16_c(ap,as,bp,bs,sse);
  case 50: return aom_highbd_12_variance64x16_c(ap,as,bp,bs,sse);
  case 51: return aom_highbd_8_variance64x32_c(ap,as,bp,bs,sse);
  case 52: return aom_highbd_10_variance64x32_c(ap,as,bp,bs,sse);
  case 53: return aom_highbd_12_variance64x32_c(ap,as,bp,bs,sse);
  case 54: return aom_highbd_8_variance64x64_c(ap,as,bp,bs,sse);
  case 55: return aom_highbd_10_variance64x64_c(ap,as,bp,bs,sse);
  case 56: return aom_highbd_12_variance64x64_c(ap,as,bp,bs,sse);
  case 57: return aom_highbd_8_variance64x128_c(ap,as,bp,bs,sse);
  case 58: return aom_highbd_10_variance64x128_c(ap,as,bp,bs,sse);
  case 59: return aom_highbd_12_variance64x128_c(ap,as,bp,bs,sse);
  case 60: return aom_highbd_8_variance128x64_c(ap,as,bp,bs,sse);
  case 61: return aom_highbd_10_variance128x64_c(ap,as,bp,bs,sse);
  case 62: return aom_highbd_12_variance128x64_c(ap,as,bp,bs,sse);
  case 63: return aom_highbd_8_variance128x128_c(ap,as,bp,bs,sse);
  case 64: return aom_highbd_10_variance128x128_c(ap,as,bp,bs,sse);
  case 65: return aom_highbd_12_variance128x128_c(ap,as,bp,bs,sse);
  default: return 0;}}

/* highbd sub-pixel variance (bilinear 2-tap) */
uint32_t aom_highbd_8_sub_pixel_variance4x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance4x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance4x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance4x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance4x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance4x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance4x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance4x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance4x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance8x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance8x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance8x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance8x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance8x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance8x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance8x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance8x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance8x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance8x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance8x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance8x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance16x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance16x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance16x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance16x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance16x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance16x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance16x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance16x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance16x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance16x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance16x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance16x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance16x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance16x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance16x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance32x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance32x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance32x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance32x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance32x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance32x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance32x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance32x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance32x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance32x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance32x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance32x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance64x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance64x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance64x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance64x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance64x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance64x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance64x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance64x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance64x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance64x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance64x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance64x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance128x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance128x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance128x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_8_sub_pixel_variance128x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_10_sub_pixel_variance128x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t aom_highbd_12_sub_pixel_variance128x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
uint32_t shim_hbd_subpel_var(int i,int bd,const uint16_t*a,int as,int xo,int yo,const uint16_t*b,int bs,uint32_t*sse){
  const uint8_t* ap=CONVERT_TO_BYTEPTR(a); const uint8_t* bp=CONVERT_TO_BYTEPTR(b);
  switch(i*3 + (bd==8?0:bd==10?1:2)){
  case 0: return aom_highbd_8_sub_pixel_variance4x4_c(ap,as,xo,yo,bp,bs,sse);
  case 1: return aom_highbd_10_sub_pixel_variance4x4_c(ap,as,xo,yo,bp,bs,sse);
  case 2: return aom_highbd_12_sub_pixel_variance4x4_c(ap,as,xo,yo,bp,bs,sse);
  case 3: return aom_highbd_8_sub_pixel_variance4x8_c(ap,as,xo,yo,bp,bs,sse);
  case 4: return aom_highbd_10_sub_pixel_variance4x8_c(ap,as,xo,yo,bp,bs,sse);
  case 5: return aom_highbd_12_sub_pixel_variance4x8_c(ap,as,xo,yo,bp,bs,sse);
  case 6: return aom_highbd_8_sub_pixel_variance4x16_c(ap,as,xo,yo,bp,bs,sse);
  case 7: return aom_highbd_10_sub_pixel_variance4x16_c(ap,as,xo,yo,bp,bs,sse);
  case 8: return aom_highbd_12_sub_pixel_variance4x16_c(ap,as,xo,yo,bp,bs,sse);
  case 9: return aom_highbd_8_sub_pixel_variance8x4_c(ap,as,xo,yo,bp,bs,sse);
  case 10: return aom_highbd_10_sub_pixel_variance8x4_c(ap,as,xo,yo,bp,bs,sse);
  case 11: return aom_highbd_12_sub_pixel_variance8x4_c(ap,as,xo,yo,bp,bs,sse);
  case 12: return aom_highbd_8_sub_pixel_variance8x8_c(ap,as,xo,yo,bp,bs,sse);
  case 13: return aom_highbd_10_sub_pixel_variance8x8_c(ap,as,xo,yo,bp,bs,sse);
  case 14: return aom_highbd_12_sub_pixel_variance8x8_c(ap,as,xo,yo,bp,bs,sse);
  case 15: return aom_highbd_8_sub_pixel_variance8x16_c(ap,as,xo,yo,bp,bs,sse);
  case 16: return aom_highbd_10_sub_pixel_variance8x16_c(ap,as,xo,yo,bp,bs,sse);
  case 17: return aom_highbd_12_sub_pixel_variance8x16_c(ap,as,xo,yo,bp,bs,sse);
  case 18: return aom_highbd_8_sub_pixel_variance8x32_c(ap,as,xo,yo,bp,bs,sse);
  case 19: return aom_highbd_10_sub_pixel_variance8x32_c(ap,as,xo,yo,bp,bs,sse);
  case 20: return aom_highbd_12_sub_pixel_variance8x32_c(ap,as,xo,yo,bp,bs,sse);
  case 21: return aom_highbd_8_sub_pixel_variance16x4_c(ap,as,xo,yo,bp,bs,sse);
  case 22: return aom_highbd_10_sub_pixel_variance16x4_c(ap,as,xo,yo,bp,bs,sse);
  case 23: return aom_highbd_12_sub_pixel_variance16x4_c(ap,as,xo,yo,bp,bs,sse);
  case 24: return aom_highbd_8_sub_pixel_variance16x8_c(ap,as,xo,yo,bp,bs,sse);
  case 25: return aom_highbd_10_sub_pixel_variance16x8_c(ap,as,xo,yo,bp,bs,sse);
  case 26: return aom_highbd_12_sub_pixel_variance16x8_c(ap,as,xo,yo,bp,bs,sse);
  case 27: return aom_highbd_8_sub_pixel_variance16x16_c(ap,as,xo,yo,bp,bs,sse);
  case 28: return aom_highbd_10_sub_pixel_variance16x16_c(ap,as,xo,yo,bp,bs,sse);
  case 29: return aom_highbd_12_sub_pixel_variance16x16_c(ap,as,xo,yo,bp,bs,sse);
  case 30: return aom_highbd_8_sub_pixel_variance16x32_c(ap,as,xo,yo,bp,bs,sse);
  case 31: return aom_highbd_10_sub_pixel_variance16x32_c(ap,as,xo,yo,bp,bs,sse);
  case 32: return aom_highbd_12_sub_pixel_variance16x32_c(ap,as,xo,yo,bp,bs,sse);
  case 33: return aom_highbd_8_sub_pixel_variance16x64_c(ap,as,xo,yo,bp,bs,sse);
  case 34: return aom_highbd_10_sub_pixel_variance16x64_c(ap,as,xo,yo,bp,bs,sse);
  case 35: return aom_highbd_12_sub_pixel_variance16x64_c(ap,as,xo,yo,bp,bs,sse);
  case 36: return aom_highbd_8_sub_pixel_variance32x8_c(ap,as,xo,yo,bp,bs,sse);
  case 37: return aom_highbd_10_sub_pixel_variance32x8_c(ap,as,xo,yo,bp,bs,sse);
  case 38: return aom_highbd_12_sub_pixel_variance32x8_c(ap,as,xo,yo,bp,bs,sse);
  case 39: return aom_highbd_8_sub_pixel_variance32x16_c(ap,as,xo,yo,bp,bs,sse);
  case 40: return aom_highbd_10_sub_pixel_variance32x16_c(ap,as,xo,yo,bp,bs,sse);
  case 41: return aom_highbd_12_sub_pixel_variance32x16_c(ap,as,xo,yo,bp,bs,sse);
  case 42: return aom_highbd_8_sub_pixel_variance32x32_c(ap,as,xo,yo,bp,bs,sse);
  case 43: return aom_highbd_10_sub_pixel_variance32x32_c(ap,as,xo,yo,bp,bs,sse);
  case 44: return aom_highbd_12_sub_pixel_variance32x32_c(ap,as,xo,yo,bp,bs,sse);
  case 45: return aom_highbd_8_sub_pixel_variance32x64_c(ap,as,xo,yo,bp,bs,sse);
  case 46: return aom_highbd_10_sub_pixel_variance32x64_c(ap,as,xo,yo,bp,bs,sse);
  case 47: return aom_highbd_12_sub_pixel_variance32x64_c(ap,as,xo,yo,bp,bs,sse);
  case 48: return aom_highbd_8_sub_pixel_variance64x16_c(ap,as,xo,yo,bp,bs,sse);
  case 49: return aom_highbd_10_sub_pixel_variance64x16_c(ap,as,xo,yo,bp,bs,sse);
  case 50: return aom_highbd_12_sub_pixel_variance64x16_c(ap,as,xo,yo,bp,bs,sse);
  case 51: return aom_highbd_8_sub_pixel_variance64x32_c(ap,as,xo,yo,bp,bs,sse);
  case 52: return aom_highbd_10_sub_pixel_variance64x32_c(ap,as,xo,yo,bp,bs,sse);
  case 53: return aom_highbd_12_sub_pixel_variance64x32_c(ap,as,xo,yo,bp,bs,sse);
  case 54: return aom_highbd_8_sub_pixel_variance64x64_c(ap,as,xo,yo,bp,bs,sse);
  case 55: return aom_highbd_10_sub_pixel_variance64x64_c(ap,as,xo,yo,bp,bs,sse);
  case 56: return aom_highbd_12_sub_pixel_variance64x64_c(ap,as,xo,yo,bp,bs,sse);
  case 57: return aom_highbd_8_sub_pixel_variance64x128_c(ap,as,xo,yo,bp,bs,sse);
  case 58: return aom_highbd_10_sub_pixel_variance64x128_c(ap,as,xo,yo,bp,bs,sse);
  case 59: return aom_highbd_12_sub_pixel_variance64x128_c(ap,as,xo,yo,bp,bs,sse);
  case 60: return aom_highbd_8_sub_pixel_variance128x64_c(ap,as,xo,yo,bp,bs,sse);
  case 61: return aom_highbd_10_sub_pixel_variance128x64_c(ap,as,xo,yo,bp,bs,sse);
  case 62: return aom_highbd_12_sub_pixel_variance128x64_c(ap,as,xo,yo,bp,bs,sse);
  case 63: return aom_highbd_8_sub_pixel_variance128x128_c(ap,as,xo,yo,bp,bs,sse);
  case 64: return aom_highbd_10_sub_pixel_variance128x128_c(ap,as,xo,yo,bp,bs,sse);
  case 65: return aom_highbd_12_sub_pixel_variance128x128_c(ap,as,xo,yo,bp,bs,sse);
  default: return 0;}}

/* highbd avg SAD (compound prediction); 17 non-4-side sizes */
unsigned int aom_highbd_sad8x8_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad8x16_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad8x32_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad16x8_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad16x16_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad16x32_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad16x64_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad32x8_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad32x16_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad32x32_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad32x64_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad64x16_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad64x32_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad64x64_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad64x128_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad128x64_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int aom_highbd_sad128x128_avg_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*);
unsigned int shim_hbd_sad_avg(int i,const uint16_t*s,int ss,const uint16_t*r,int rs,const uint16_t*p){
  const uint8_t* sp8=CONVERT_TO_BYTEPTR(s); const uint8_t* rp=CONVERT_TO_BYTEPTR(r); const uint8_t* pp=CONVERT_TO_BYTEPTR(p);
  switch(i){
  case 4: return aom_highbd_sad8x8_avg_c(sp8,ss,rp,rs,pp);
  case 5: return aom_highbd_sad8x16_avg_c(sp8,ss,rp,rs,pp);
  case 6: return aom_highbd_sad8x32_avg_c(sp8,ss,rp,rs,pp);
  case 8: return aom_highbd_sad16x8_avg_c(sp8,ss,rp,rs,pp);
  case 9: return aom_highbd_sad16x16_avg_c(sp8,ss,rp,rs,pp);
  case 10: return aom_highbd_sad16x32_avg_c(sp8,ss,rp,rs,pp);
  case 11: return aom_highbd_sad16x64_avg_c(sp8,ss,rp,rs,pp);
  case 12: return aom_highbd_sad32x8_avg_c(sp8,ss,rp,rs,pp);
  case 13: return aom_highbd_sad32x16_avg_c(sp8,ss,rp,rs,pp);
  case 14: return aom_highbd_sad32x32_avg_c(sp8,ss,rp,rs,pp);
  case 15: return aom_highbd_sad32x64_avg_c(sp8,ss,rp,rs,pp);
  case 16: return aom_highbd_sad64x16_avg_c(sp8,ss,rp,rs,pp);
  case 17: return aom_highbd_sad64x32_avg_c(sp8,ss,rp,rs,pp);
  case 18: return aom_highbd_sad64x64_avg_c(sp8,ss,rp,rs,pp);
  case 19: return aom_highbd_sad64x128_avg_c(sp8,ss,rp,rs,pp);
  case 20: return aom_highbd_sad128x64_avg_c(sp8,ss,rp,rs,pp);
  case 21: return aom_highbd_sad128x128_avg_c(sp8,ss,rp,rs,pp);
  default: return 0;}}

/* highbd masked SAD (wedge / diff-weighted compound), all 22 sizes */
unsigned int aom_highbd_masked_sad4x4_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad4x8_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad4x16_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad8x4_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad8x8_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad8x16_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad8x32_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad16x4_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad16x8_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad16x16_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad16x32_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad16x64_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad32x8_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad32x16_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad32x32_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad32x64_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad64x16_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad64x32_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad64x64_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad64x128_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad128x64_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int aom_highbd_masked_sad128x128_c(const uint8_t*,int,const uint8_t*,int,const uint8_t*,const uint8_t*,int,int);
unsigned int shim_hbd_masked_sad(int i,const uint16_t*s,int ss,const uint16_t*r,int rs,const uint16_t*p,const uint8_t*m,int ms,int inv){
  const uint8_t* sp8=CONVERT_TO_BYTEPTR(s); const uint8_t* rp=CONVERT_TO_BYTEPTR(r); const uint8_t* pp=CONVERT_TO_BYTEPTR(p);
  switch(i){
  case 0: return aom_highbd_masked_sad4x4_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 1: return aom_highbd_masked_sad4x8_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 2: return aom_highbd_masked_sad4x16_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 3: return aom_highbd_masked_sad8x4_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 4: return aom_highbd_masked_sad8x8_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 5: return aom_highbd_masked_sad8x16_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 6: return aom_highbd_masked_sad8x32_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 7: return aom_highbd_masked_sad16x4_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 8: return aom_highbd_masked_sad16x8_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 9: return aom_highbd_masked_sad16x16_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 10: return aom_highbd_masked_sad16x32_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 11: return aom_highbd_masked_sad16x64_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 12: return aom_highbd_masked_sad32x8_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 13: return aom_highbd_masked_sad32x16_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 14: return aom_highbd_masked_sad32x32_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 15: return aom_highbd_masked_sad32x64_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 16: return aom_highbd_masked_sad64x16_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 17: return aom_highbd_masked_sad64x32_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 18: return aom_highbd_masked_sad64x64_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 19: return aom_highbd_masked_sad64x128_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 20: return aom_highbd_masked_sad128x64_c(sp8,ss,rp,rs,pp,m,ms,inv);
  case 21: return aom_highbd_masked_sad128x128_c(sp8,ss,rp,rs,pp,m,ms,inv);
  default: return 0;}}

/* highbd OBMC SAD, all 22 sizes */
unsigned int aom_highbd_obmc_sad4x4_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad4x8_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad4x16_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad8x4_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad8x8_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad8x16_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad8x32_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad16x4_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad16x8_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad16x16_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad16x32_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad16x64_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad32x8_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad32x16_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad32x32_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad32x64_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad64x16_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad64x32_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad64x64_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad64x128_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad128x64_c(const uint8_t*,int,const int*,const int*);
unsigned int aom_highbd_obmc_sad128x128_c(const uint8_t*,int,const int*,const int*);
unsigned int shim_hbd_obmc_sad(int i,const uint16_t*r,int rs,const int*ws,const int*m){
  const uint8_t* rp=CONVERT_TO_BYTEPTR(r);
  switch(i){
  case 0: return aom_highbd_obmc_sad4x4_c(rp,rs,ws,m);
  case 1: return aom_highbd_obmc_sad4x8_c(rp,rs,ws,m);
  case 2: return aom_highbd_obmc_sad4x16_c(rp,rs,ws,m);
  case 3: return aom_highbd_obmc_sad8x4_c(rp,rs,ws,m);
  case 4: return aom_highbd_obmc_sad8x8_c(rp,rs,ws,m);
  case 5: return aom_highbd_obmc_sad8x16_c(rp,rs,ws,m);
  case 6: return aom_highbd_obmc_sad8x32_c(rp,rs,ws,m);
  case 7: return aom_highbd_obmc_sad16x4_c(rp,rs,ws,m);
  case 8: return aom_highbd_obmc_sad16x8_c(rp,rs,ws,m);
  case 9: return aom_highbd_obmc_sad16x16_c(rp,rs,ws,m);
  case 10: return aom_highbd_obmc_sad16x32_c(rp,rs,ws,m);
  case 11: return aom_highbd_obmc_sad16x64_c(rp,rs,ws,m);
  case 12: return aom_highbd_obmc_sad32x8_c(rp,rs,ws,m);
  case 13: return aom_highbd_obmc_sad32x16_c(rp,rs,ws,m);
  case 14: return aom_highbd_obmc_sad32x32_c(rp,rs,ws,m);
  case 15: return aom_highbd_obmc_sad32x64_c(rp,rs,ws,m);
  case 16: return aom_highbd_obmc_sad64x16_c(rp,rs,ws,m);
  case 17: return aom_highbd_obmc_sad64x32_c(rp,rs,ws,m);
  case 18: return aom_highbd_obmc_sad64x64_c(rp,rs,ws,m);
  case 19: return aom_highbd_obmc_sad64x128_c(rp,rs,ws,m);
  case 20: return aom_highbd_obmc_sad128x64_c(rp,rs,ws,m);
  case 21: return aom_highbd_obmc_sad128x128_c(rp,rs,ws,m);
  default: return 0;}}

/* highbd SSE */
int64_t aom_highbd_sse_c(const uint8_t*,int,const uint8_t*,int,int,int);
int64_t shim_hbd_sse(const uint16_t*a,int as,const uint16_t*b,int bs,int w,int h){
  return aom_highbd_sse_c(CONVERT_TO_BYTEPTR(a),as,CONVERT_TO_BYTEPTR(b),bs,w,h);}
