/* GENERATED SAD/variance dispatch shim. Oracle use only. */
#include <stdint.h>
unsigned int aom_sad4x4_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance4x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance4x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad4x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance4x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance4x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad4x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance4x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance4x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad8x4_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance8x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance8x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad8x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance8x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance8x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad8x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance8x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance8x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad8x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance8x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance8x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad16x4_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance16x4_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance16x4_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad16x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance16x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance16x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad16x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance16x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance16x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad16x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance16x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance16x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad16x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance16x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance16x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad32x8_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance32x8_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance32x8_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad32x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance32x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance32x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad32x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance32x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance32x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad32x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance32x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance32x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad64x16_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance64x16_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance64x16_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad64x32_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance64x32_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance64x32_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad64x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance64x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance64x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad64x128_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance64x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance64x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad128x64_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance128x64_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance128x64_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int aom_sad128x128_c(const uint8_t*,int,const uint8_t*,int);
uint32_t aom_variance128x128_c(const uint8_t*,int,const uint8_t*,int,uint32_t*);
uint32_t aom_sub_pixel_variance128x128_c(const uint8_t*,int,int,int,const uint8_t*,int,uint32_t*);
unsigned int shim_sad(int i,const uint8_t*s,int ss,const uint8_t*r,int rs){switch(i){
case 0:return aom_sad4x4_c(s,ss,r,rs);
case 1:return aom_sad4x8_c(s,ss,r,rs);
case 2:return aom_sad4x16_c(s,ss,r,rs);
case 3:return aom_sad8x4_c(s,ss,r,rs);
case 4:return aom_sad8x8_c(s,ss,r,rs);
case 5:return aom_sad8x16_c(s,ss,r,rs);
case 6:return aom_sad8x32_c(s,ss,r,rs);
case 7:return aom_sad16x4_c(s,ss,r,rs);
case 8:return aom_sad16x8_c(s,ss,r,rs);
case 9:return aom_sad16x16_c(s,ss,r,rs);
case 10:return aom_sad16x32_c(s,ss,r,rs);
case 11:return aom_sad16x64_c(s,ss,r,rs);
case 12:return aom_sad32x8_c(s,ss,r,rs);
case 13:return aom_sad32x16_c(s,ss,r,rs);
case 14:return aom_sad32x32_c(s,ss,r,rs);
case 15:return aom_sad32x64_c(s,ss,r,rs);
case 16:return aom_sad64x16_c(s,ss,r,rs);
case 17:return aom_sad64x32_c(s,ss,r,rs);
case 18:return aom_sad64x64_c(s,ss,r,rs);
case 19:return aom_sad64x128_c(s,ss,r,rs);
case 20:return aom_sad128x64_c(s,ss,r,rs);
case 21:return aom_sad128x128_c(s,ss,r,rs);
default:return 0;}}
uint32_t shim_variance(int i,const uint8_t*a,int as,const uint8_t*b,int bs,uint32_t*sse){switch(i){
case 0:return aom_variance4x4_c(a,as,b,bs,sse);
case 1:return aom_variance4x8_c(a,as,b,bs,sse);
case 2:return aom_variance4x16_c(a,as,b,bs,sse);
case 3:return aom_variance8x4_c(a,as,b,bs,sse);
case 4:return aom_variance8x8_c(a,as,b,bs,sse);
case 5:return aom_variance8x16_c(a,as,b,bs,sse);
case 6:return aom_variance8x32_c(a,as,b,bs,sse);
case 7:return aom_variance16x4_c(a,as,b,bs,sse);
case 8:return aom_variance16x8_c(a,as,b,bs,sse);
case 9:return aom_variance16x16_c(a,as,b,bs,sse);
case 10:return aom_variance16x32_c(a,as,b,bs,sse);
case 11:return aom_variance16x64_c(a,as,b,bs,sse);
case 12:return aom_variance32x8_c(a,as,b,bs,sse);
case 13:return aom_variance32x16_c(a,as,b,bs,sse);
case 14:return aom_variance32x32_c(a,as,b,bs,sse);
case 15:return aom_variance32x64_c(a,as,b,bs,sse);
case 16:return aom_variance64x16_c(a,as,b,bs,sse);
case 17:return aom_variance64x32_c(a,as,b,bs,sse);
case 18:return aom_variance64x64_c(a,as,b,bs,sse);
case 19:return aom_variance64x128_c(a,as,b,bs,sse);
case 20:return aom_variance128x64_c(a,as,b,bs,sse);
case 21:return aom_variance128x128_c(a,as,b,bs,sse);
default:return 0;}}
uint32_t shim_subpel_var(int i,const uint8_t*a,int as,int xo,int yo,const uint8_t*b,int bs,uint32_t*sse){switch(i){
case 0:return aom_sub_pixel_variance4x4_c(a,as,xo,yo,b,bs,sse);
case 1:return aom_sub_pixel_variance4x8_c(a,as,xo,yo,b,bs,sse);
case 2:return aom_sub_pixel_variance4x16_c(a,as,xo,yo,b,bs,sse);
case 3:return aom_sub_pixel_variance8x4_c(a,as,xo,yo,b,bs,sse);
case 4:return aom_sub_pixel_variance8x8_c(a,as,xo,yo,b,bs,sse);
case 5:return aom_sub_pixel_variance8x16_c(a,as,xo,yo,b,bs,sse);
case 6:return aom_sub_pixel_variance8x32_c(a,as,xo,yo,b,bs,sse);
case 7:return aom_sub_pixel_variance16x4_c(a,as,xo,yo,b,bs,sse);
case 8:return aom_sub_pixel_variance16x8_c(a,as,xo,yo,b,bs,sse);
case 9:return aom_sub_pixel_variance16x16_c(a,as,xo,yo,b,bs,sse);
case 10:return aom_sub_pixel_variance16x32_c(a,as,xo,yo,b,bs,sse);
case 11:return aom_sub_pixel_variance16x64_c(a,as,xo,yo,b,bs,sse);
case 12:return aom_sub_pixel_variance32x8_c(a,as,xo,yo,b,bs,sse);
case 13:return aom_sub_pixel_variance32x16_c(a,as,xo,yo,b,bs,sse);
case 14:return aom_sub_pixel_variance32x32_c(a,as,xo,yo,b,bs,sse);
case 15:return aom_sub_pixel_variance32x64_c(a,as,xo,yo,b,bs,sse);
case 16:return aom_sub_pixel_variance64x16_c(a,as,xo,yo,b,bs,sse);
case 17:return aom_sub_pixel_variance64x32_c(a,as,xo,yo,b,bs,sse);
case 18:return aom_sub_pixel_variance64x64_c(a,as,xo,yo,b,bs,sse);
case 19:return aom_sub_pixel_variance64x128_c(a,as,xo,yo,b,bs,sse);
case 20:return aom_sub_pixel_variance128x64_c(a,as,xo,yo,b,bs,sse);
case 21:return aom_sub_pixel_variance128x128_c(a,as,xo,yo,b,bs,sse);
default:return 0;}}
